[build]
  publish = "dist"
  command = "yarn build"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"

[dev]
  command = "yarn dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
